name: Release

on:
  push:
    branches: [master]
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASER_TOKEN }}
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json
